### PR TITLE
Thibaultmh/proposed fix to decode id token without kid in alg header

### PR DESCRIPTION
**Pull request by thibault-tiro**
> DO NOT SEND ANY SECURITY FIX HERE. Please read "Security Reporting" section
> on README.

**What kind of change does this PR introduce?** (check at least one)

- [X] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [X] No

---

- [X] You consent that the copyright of your pull request source code belongs to Authlib's author.

### CODE REVIEW

**Review by codespearhead — APPROVED** [review]
[As per section 4.5 of RFC 7517](https://datatracker.ietf.org/doc/html/rfc7517#section-4.5), the "kid" (Key ID) parameter is optional.

**Comment by axelv** [comment]
First of all thx for maintaining this awesome library.
Any perspective on when this PR will be released?

**Comment by lepture** [comment]
Thanks for the fix.

**Comment by FrancisRalph** [comment]
Was about to raise a PR for this, thanks! Would it be possible to bump the version? @lepture

**Pull request merged**
