### PR TITLE
Restore behaviour in create_authorization_response call which previously accepted a OAuth2Request object as-is

### PR DESCRIPTION
**Pull request by TurnrDev**
**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No - rather, fixes one. Explaination [here](https://github.com/lepture/authlib/commit/c060dab824f14929d33a567880042b026ed11b1b#r119835558)

---

- [x] You consent that the copyright of your pull request source code belongs to Authlib's author.

### CODE REVIEW

**Comment by lepture** [comment]
Thanks

**Comment by TurnrDev** [comment]
Amazing, I wasn't sure if this was going to be accepted or not! 

Would you accept PRs that add support for more OIDC stuff? I unfortunately noticed this library doesn't supply any framework or even documentation on how to implement /.well-known/openid-configuration or JWKS endpoints.

**Comment by cas--** [comment]
Thanks @TurnrDev, this caught me out migrating old code based on Authlib 0.12 with custom `create_oauth_request`

Until this is released I am using a modified AuthorizationServer

```
from authlib.oauth2 import OAuth2Request
from authlib.integrations.flask_oauth2 import (
    AuthorizationServer as _AuthorizationServer,
)

class AuthorizationServer(_AuthorizationServer):
    def create_oauth2_request(self, request):
        if isinstance(request, OAuth2Request):
            return request

        return super().create_oauth2_request(request)
```

**Comment by azmeuk** [comment]
> Would you accept PRs that add support for more OIDC stuff? I unfortunately noticed this library doesn't supply any framework or even documentation on how to implement /.well-known/openid-configuration or JWKS endpoints.

Hi @TurnrDev 
Better late than never. I would gladly review your PRs if you want to contribute to Authlib :)

**Pull request merged**
