### PR TITLE
Add sync HTTPX AssertionClient and OAuth2Client

### PR DESCRIPTION
**Pull request by ulodciv**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No (I think)

---

- [x] You consent that the copyright of your pull request source code belongs to Authlib's author.

### CODE REVIEW

**Comment by phy25** [comment]
I think the sync support was dropped intentionally: https://github.com/lepture/authlib/releases/tag/v0.14

**Comment by ulodciv** [comment]
> I think the sync support was dropped intentionally: https://github.com/lepture/authlib/releases/tag/v0.14

Yea I saw that, but why? HTTPX is meant to support sync and async as of [0.11](https://github.com/encode/httpx/blob/master/CHANGELOG.md#0110-january-9th-2020) ("HTTPX is a fully featured HTTP client for Python 3, which provides sync and async APIs, and support for both HTTP/1.1 and HTTP/2."). My understanding is that this will stay as it is necessary for HTTPX to remain a quasi drop-in replacement for requests (see [the first item](https://github.com/encode/httpx#features) in the feature list).

**Comment by lepture** [comment]
HTTPX changes very quickly, it once dropped support for sync mode, that is when Authlib removed sync client. I'm not sure if they will drop sync client again. I'll wait until it reaches 1.0.

**Comment by ulodciv** [comment]
@lepture 
 
I totally understand what you mean, but the fact remains that the main path to adoption of HTTPX from requests is to use HTTPX's non-async objects, I think. In any case, I just put the additional objects proposed in this PR in my projects for now.

**Pull request closed without merging**
