### PR TITLE
add google_fetch_user function

### PR DESCRIPTION
**Pull request by greyli**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [x] Other, please describe:

Thsi PR add `google_fetch_user()` function for the built-in google client.

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

**The PR fulfills these requirements:**

- [x] Test cases.

### CODE REVIEW

**Comment by lepture** [comment]
Thank you.

**Comment by greyli** [comment]
You are welcome. IMO, it would be more helpful to return the profile response directly.

**Comment by lepture** [comment]
@greyli I'm planning to rewrite the whole client apps. It should be refactored when Django integration finished.

**Comment by greyli** [comment]
That's great!

**Pull request merged**
