### PR TITLE
Check actual headers

### PR DESCRIPTION
**Pull request by snznedta**
**What kind of change does this PR introduce?** (check at least one)
Fix a bug that not adding unprotected headers to signatures.
- [x] Bugfix

**Does this PR introduce a breaking change?** (check one)

- [x] No

---

- [x] You consent that the copyright of your pull request source code belongs to Authlib's author.

### CODE REVIEW

**Comment by lepture** [comment]
Thanks, but you got it wrong. The original implementation is right, but the logic is not well to understand, I will change it.

**Comment by lepture** [comment]
Thanks. I'm doing a lot of refactoring right now, because of https://github.com/lepture/authlib/issues/65 I will take it into the refactoring.

**Comment by lepture** [comment]
It is fixed in the `feature-jwe` branch.

**Comment by snznedta** [comment]
Thanks for addressing that!

**Pull request closed without merging**
