### PR TITLE
Modify _HTTPException to work with werkzeug 2.0.0

### PR DESCRIPTION
**Pull request by charity-detalytics**
> DO NOT SEND ANY SECURITY FIX HERE. Please read "Security Reporting" section
> on README.

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

---

- [x] You consent that the copyright of your pull request source code belongs to Authlib's author.

### CODE REVIEW

**Comment by MaicoTimmerman** [comment]
@lepture I'd love to see this PR get released, as it holds back from using Flask 2.0 and Werkzeug 2.0

**Comment by lepture** [comment]
Can you add a check of werkzeug version? Define `_HTTPException` varies with werkzeug version.

**Comment by lepture** [comment]
I've added the check.

**Comment by m-aciek** [comment]
Thank you!

**Comment by po5i** [comment]
Thank you!

**Pull request merged**
