### PR TITLE
Implement OAuth2 for httpx streaming requests

### PR DESCRIPTION
**Pull request by rogiervandergeer**
> DO NOT SEND ANY SECURITY FIX HERE. Please read "Security Reporting" section
> on README.

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

---

- [x] You consent that the copyright of your pull request source code belongs to Authlib's author.

### CODE REVIEW

**Review by ulodciv — APPROVED** [review]
I tested adding the non-async `stream` method and it worked well. Cool stuff!

**Comment by lepture** [comment]
Thanks

**Comment by ulodciv** [comment]
@lepture 
Any chance for a quick new alpha on pypi?

**Comment by lepture** [comment]
@ulodciv I'll make a release after I removed sqlalchemy integration.

**Pull request merged**
