### PR TITLE
Support Custom Grant Type when fetching tokens with Username/Password

### PR DESCRIPTION
**Pull request by lawliet89**
For example, this allows use with some custom grant type with
username/password like Auth0's "Realm Support":
https://auth0.com/docs/api-auth/tutorials/password-grant#realm-support

**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [x] Other, please describe:

Allow additional option for users.

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

(If no, please delete the above question and this text message.)

---

- [x] You consent that the copyright of your pull request source code belongs to Authlib's author.

### CODE REVIEW

**Comment by lepture** [comment]
@lawliet89 This is not a common use case. And the examples on Auth0 are using `grant_type=password`

**Comment by lawliet89** [comment]
I don't think there is any harm allowing the user to override the grant
type.

The code example disagrees with the prose. I need to use their custom grant
type to work with realm.

**Comment by JonathanHuot** [comment]
I don't know if it helps, but in oauthlib, we have moved grant-type which were hard-coded into class variables to help developers to change the `grant_type` values, if they want to. However, I agree it should not be pollute the API/code for these edge-cases.

**Comment by lawliet89** [comment]
Would you mind sharing an example on how to do this?

**Comment by lawliet89** [comment]
@JonathanHuot I disagree that my changes pollutes the code. The way I see it, it's no different from how the PR you linked allows the user to override the `grant_type`.

**Comment by bjmc** [comment]
I think "pollute" might not be a helpful word here, because it has such a negative connotation. [The change]( https://github.com/oauthlib/oauthlib/pull/625/files) in oauthlib allows overriding the `grant_type`, but only by subclassing or monkey-patching the client object. Arguably, that's better because it gives callers who really need it the chance to change that parameter, but it doesn't burden "normal" users with worrying about an extra keyword argument.

On the other hand, an optional keyword with a sensible default value doesn't seem a terrible burden, and the `fetch_token()` method [already accepts a `grant_type` kwarg](https://github.com/lepture/authlib/blob/d3e180477a57faf1b56919d00e2be8574825911f/authlib/oauth2/client.py#L165), but only uses it in cases where `username` and `password` aren't set. As a consumer of the API, I think it would be simpler if overriding `grant_type` were either allowed or disallowed in all cases. As it stands, you have to deal with 'you can override the `grant_type`, but not if you're sending a password', which is a more complex rule.

**Comment by lawliet89** [comment]
> On the other hand, an optional keyword with a sensible default value doesn't seem a terrible burden, and the `fetch_token()` method [already accepts a `grant_type` kwarg](https://github.com/lepture/authlib/blob/d3e180477a57faf1b56919d00e2be8574825911f/authlib/oauth2/client.py#L165), but only uses it in cases where `username` and `password` aren't set. As a consumer of the API, I think it would be simpler if overriding `grant_type` were either allowed or disallowed in all cases. As it stands, you have to deal with 'you can override the `grant_type`, but not if you're sending a password', which is a more complex rule.

Exactly. I had to peruse the source code to see where a preset `grant_type` is coming from. This was rather surprising to me.

**Comment by JonathanHuot** [comment]
@lawliet89, I didn't wanted to add much attention on the pollute word sorry, I just wanted to highlight the key differences between the standards, the customization and their exceptions.

When you read the authlib code, do you prefer to clearly understand the purpose of the standard ? `grant_type=password` is clearly defined and we have a single way to define it.

Or do you prefer to be flooded by yet another-kwargs which has no other values in the specification and thus, leading the developers to be confused on the purpose of the API and how can we use it properly: e.g. do I need to add `grant_type=password` to my function call ? do I have other options ?
 
My belief is that whenever a `kwargs` can be avoided, just avoid it. As @bjmc said, moving this possibility to the class variable to allow subclassing the `OAuth2Client` for a custom use-case seems more reasonnable to me. However that's the @lepture call.

**Comment by lawliet89** [comment]
@JonathanHuot Sure. I agree with you. (Pardon me for my ignorance, what is the relationship between  `authlib` and `oauthlib`?)

In any case, `authlib` currently has the same behaviour for stuff that do not involve username/passwords and for the sake of consistency, i would argue that this PR would make it more consistent and make custom use cases possible.

**Pull request merged**
